### ISSUE TITLE
Encountered error when enabling ZeRO3 and CPU Activation Checkpointing at the same time.

### ISSUE THREAD

**Issue by zincnode** [microsoft/Megatron-DeepSpeed#115]
When I was testing GPT training and enabled ZeRO-3 and CPU Activation Checkpointing at the same time, I got some errors.

At first, there are some WARNING.
```
10.0.1.101: training ...
10.0.1.99: time (ms) | model-and-optimizer-setup: 37634.40 | train/valid/test-data-iterators-setup: 119428.93
10.0.1.101: [before the start of training step] datetime: 2023-03-05 09:12:02
10.0.1.101: [2023-03-05 09:12:02,597] [INFO] [checkpointing.py:552:forward] Activation Checkpointing Information
10.0.1.101: [2023-03-05 09:12:02,597] [INFO] [checkpointing.py:553:forward] ----Partition Activations True, CPU CHECKPOINTING True
10.0.1.101: [2023-03-05 09:12:02,597] [INFO] [checkpointing.py:556:forward] ----contiguous Memory Checkpointing True with 62 total layers
10.0.1.101: [2023-03-05 09:12:02,597] [INFO] [checkpointing.py:559:forward] ----Synchronization True
10.0.1.101: [2023-03-05 09:12:02,597] [INFO] [checkpointing.py:560:forward] ----Profiling time in checkpointing False
10.0.1.101: WARNING! The input of FusedLayerNorm should be on the GPU.This warning should only be triggered in the FusedLayerNorm unit tests.
10.0.1.99: WARNING! The input of FusedLayerNorm should be on the GPU.This warning should only be triggered in the FusedLayerNorm unit tests.
10.0.1.101: WARNING! The input of FusedLayerNorm should be on the GPU.This warning should only be triggered in the FusedLayerNorm unit tests.
...
```
After that, I got errors.

<details><summary>CLICK ME</summary>
<p>

```
10.0.1.101: Traceback (most recent call last):
10.0.1.101:   File "../pretrain_gpt.py", line 326, in <module>
10.0.1.99: Traceback (most recent call last):
10.0.1.99:   File "../pretrain_gpt.py", line 326, in <module>
10.0.1.101:     pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
10.0.1.101:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 187, in pretrain
10.0.1.101:     iteration = train(forward_step_func,
10.0.1.101:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 1034, in train
10.0.1.99:     pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
10.0.1.99:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 187, in pretrain
10.0.1.99:     iteration = train(forward_step_func,
10.0.1.99:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 1034, in train
10.0.1.101:     train_step(forward_step_func,
10.0.1.101:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 607, in train_step
10.0.1.101:     losses_reduced = forward_backward_func(
10.0.1.101:   File "/workdir/2023/Megatron-DeepSpeed/megatron/schedules.py", line 161, in forward_backward_no_pipelining
10.0.1.99:     train_step(forward_step_func,
10.0.1.99:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 607, in train_step
10.0.1.101:     backward_step(optimizer, input_tensor, output_tensor, output_tensor_grad, model)
10.0.1.101:   File "/workdir/2023/Megatron-DeepSpeed/megatron/schedules.py", line 100, in backward_step
10.0.1.101:     model.backward(output_tensor)
10.0.1.101:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 9, in wrapped_fn
10.0.1.99:     losses_reduced = forward_backward_func(
10.0.1.99:   File "/workdir/2023/Megatron-DeepSpeed/megatron/schedules.py", line 161, in forward_backward_no_pipelining
10.0.1.99:     backward_step(optimizer, input_tensor, output_tensor, output_tensor_grad, model)
10.0.1.99:   File "/workdir/2023/Megatron-DeepSpeed/megatron/schedules.py", line 100, in backward_step
10.0.1.101:     ret_val = func(*args, **kwargs)
10.0.1.101:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1968, in backward
10.0.1.99:     model.backward(output_tensor)
10.0.1.99:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 9, in wrapped_fn
10.0.1.99:     ret_val = func(*args, **kwargs)
10.0.1.99:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1968, in backward
10.0.1.101:     self.optimizer.backward(loss, retain_graph=retain_graph)
10.0.1.101:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 9, in wrapped_fn
10.0.1.101:     ret_val = func(*args, **kwargs)
10.0.1.101:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 2089, in backward
10.0.1.96: Traceback (most recent call last):
10.0.1.101: Traceback (most recent call last):
10.0.1.101:   File "../pretrain_gpt.py", line 326, in <module>
10.0.1.99:     self.optimizer.backward(loss, retain_graph=retain_graph)
10.0.1.99:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 9, in wrapped_fn
10.0.1.99:     ret_val = func(*args, **kwargs)
10.0.1.99:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 2089, in backward
10.0.1.97: Traceback (most recent call last):
10.0.1.97:   File "../pretrain_gpt.py", line 326, in <module>
10.0.1.96:   File "../pretrain_gpt.py", line 326, in <module>
10.0.1.101:     self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
10.0.1.101:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 51, in backward
10.0.1.101:     pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
10.0.1.101:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 187, in pretrain
10.0.1.99:     self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
10.0.1.99:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 51, in backward
10.0.1.96:     pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
10.0.1.101:     scaled_loss.backward(retain_graph=retain_graph)
10.0.1.101:   File "/opt/conda/lib/python3.8/site-packages/torch/_tensor.py", line 402, in backward
10.0.1.96:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 187, in pretrain
10.0.1.101:     iteration = train(forward_step_func,
10.0.1.101:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 1034, in train
10.0.1.101:     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
10.0.1.96:     iteration = train(forward_step_func,
10.0.1.96:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 1034, in train
10.0.1.99:     Traceback (most recent call last):
10.0.1.99: scaled_loss.backward(retain_graph=retain_graph)
10.0.1.96: Traceback (most recent call last):
10.0.1.96:   File "../pretrain_gpt.py", line 326, in <module>
10.0.1.99:   File "/opt/conda/lib/python3.8/site-packages/torch/_tensor.py", line 402, in backward
10.0.1.101:   File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 191, in backward
10.0.1.99:   File "../pretrain_gpt.py", line 326, in <module>
10.0.1.96:     train_step(forward_step_func,
10.0.1.96:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 607, in train_step
10.0.1.101:     Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
10.0.1.99:     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
10.0.1.101:   File "/opt/conda/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
10.0.1.99:   File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 191, in backward
10.0.1.101:     train_step(forward_step_func,
10.0.1.101:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 607, in train_step
10.0.1.101:     return user_fn(self, *args)
10.0.1.97:     pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
10.0.1.97:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 187, in pretrain
10.0.1.97: Traceback (most recent call last):
10.0.1.97:   File "../pretrain_gpt.py", line 326, in <module>
10.0.1.97:     iteration = train(forward_step_func,
10.0.1.97:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 1034, in train
10.0.1.97: Traceback (most recent call last):
10.0.1.97:   File "../pretrain_gpt.py", line 326, in <module>
10.0.1.97:     train_step(forward_step_func,
10.0.1.97:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 607, in train_step
10.0.1.97:     pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
10.0.1.97:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 187, in pretrain
10.0.1.97:     losses_reduced = forward_backward_func(
10.0.1.97:   File "/workdir/2023/Megatron-DeepSpeed/megatron/schedules.py", line 161, in forward_backward_no_pipelining
10.0.1.97:     iteration = train(forward_step_func,
10.0.1.97:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 1034, in train
10.0.1.97:     backward_step(optimizer, input_tensor, output_tensor, output_tensor_grad, model)
10.0.1.97:   File "/workdir/2023/Megatron-DeepSpeed/megatron/schedules.py", line 100, in backward_step
10.0.1.97:     model.backward(output_tensor)
10.0.1.97:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 9, in wrapped_fn
10.0.1.99:     Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
10.0.1.99:   File "/opt/conda/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
10.0.1.96:     losses_reduced = forward_backward_func(
10.0.1.101:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 698, in backward
10.0.1.99:     return user_fn(self, *args)
10.0.1.99:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 698, in backward
10.0.1.99:     pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
10.0.1.99:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 187, in pretrain
10.0.1.99:     outputs = ctx.run_function(*detached_inputs)
10.0.1.99:   File "/workdir/2023/Megatron-DeepSpeed/megatron/model/transformer.py", line 710, in custom_forward
10.0.1.99:     iteration = train(forward_step_func,
10.0.1.99:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 1034, in train
10.0.1.99:     x_, moe_loss = layer(x_, attention_mask=attention_mask, encoder_output=encoder_output, enc_dec_attn_mask=enc_dec_attn_mask)
10.0.1.99:   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1204, in _call_impl
10.0.1.96:   File "/workdir/2023/Megatron-DeepSpeed/megatron/schedules.py", line 161, in forward_backward_no_pipelining
10.0.1.101:     losses_reduced = forward_backward_func(
10.0.1.101:   File "/workdir/2023/Megatron-DeepSpeed/megatron/schedules.py", line 161, in forward_backward_no_pipelining
10.0.1.101:         outputs = ctx.run_function(*detached_inputs)backward_step(optimizer, input_tensor, output_tensor, output_tensor_grad, model)
10.0.1.101:
10.0.1.99:     train_step(forward_step_func,
10.0.1.101:   File "/workdir/2023/Megatron-DeepSpeed/megatron/schedules.py", line 100, in backward_step
10.0.1.101:   File "/workdir/2023/Megatron-DeepSpeed/megatron/model/transformer.py", line 710, in custom_forward
10.0.1.101:     model.backward(output_tensor)
10.0.1.99:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 607, in train_step
10.0.1.97:     pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
10.0.1.97:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 187, in pretrain
10.0.1.101:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 9, in wrapped_fn
10.0.1.97:     ret_val = func(*args, **kwargs)
10.0.1.101:         ret_val = func(*args, **kwargs)x_, moe_loss = layer(x_, attention_mask=attention_mask, encoder_output=encoder_output, enc_dec_attn_mask=enc_dec_attn_mask)
10.0.1.101:
10.0.1.101:   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1204, in _call_impl
10.0.1.101:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1968, in backward
10.0.1.97:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1968, in backward
10.0.1.101: Traceback (most recent call last):
10.0.1.101:   File "../pretrain_gpt.py", line 326, in <module>
10.0.1.101:     result = forward_call(*input, **kwargs)
10.0.1.99:     result = forward_call(*input, **kwargs)
10.0.1.97:     train_step(forward_step_func,
10.0.1.97:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 607, in train_step
10.0.1.97:     iteration = train(forward_step_func,
10.0.1.97:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 1034, in train
10.0.1.96:     backward_step(optimizer, input_tensor, output_tensor, output_tensor_grad, model)
10.0.1.97: Traceback (most recent call last):
10.0.1.99:   File "/workdir/2023/Megatron-DeepSpeed/megatron/model/transformer.py", line 474, in forward
10.0.1.101:   File "/workdir/2023/Megatron-DeepSpeed/megatron/model/transformer.py", line 474, in forward
10.0.1.97:   File "../pretrain_gpt.py", line 326, in <module>
10.0.1.99:     losses_reduced = forward_backward_func(
10.0.1.101:     layernorm_output = self.input_layernorm(hidden_states)
10.0.1.101:   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1204, in _call_impl
10.0.1.101:     self.optimizer.backward(loss, retain_graph=retain_graph)
10.0.1.97:     losses_reduced = forward_backward_func(
10.0.1.99:   File "/workdir/2023/Megatron-DeepSpeed/megatron/schedules.py", line 161, in forward_backward_no_pipelining
10.0.1.101:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 9, in wrapped_fn
10.0.1.97:   File "/workdir/2023/Megatron-DeepSpeed/megatron/schedules.py", line 161, in forward_backward_no_pipelining
10.0.1.101:     ret_val = func(*args, **kwargs)
10.0.1.97:     backward_step(optimizer, input_tensor, output_tensor, output_tensor_grad, model)
10.0.1.97:   File "/workdir/2023/Megatron-DeepSpeed/megatron/schedules.py", line 100, in backward_step
10.0.1.101:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 2089, in backward
10.0.1.99:     layernorm_output = self.input_layernorm(hidden_states)
10.0.1.99:   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1204, in _call_impl
10.0.1.99:     backward_step(optimizer, input_tensor, output_tensor, output_tensor_grad, model)
10.0.1.99:   File "/workdir/2023/Megatron-DeepSpeed/megatron/schedules.py", line 100, in backward_step
10.0.1.101:     pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
10.0.1.101:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 187, in pretrain
10.0.1.101:     result = forward_call(*input, **kwargs)
10.0.1.101:   File "/workdir/2023/Megatron-DeepSpeed/megatron/model/fused_layer_norm.py", line 92, in forward
10.0.1.101:         iteration = train(forward_step_func,return F.layer_norm(input, self.normalized_shape, self.weight, self.bias, self.eps)
10.0.1.101:
10.0.1.101:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 1034, in train
10.0.1.101:   File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2509, in layer_norm
10.0.1.101:     self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
10.0.1.101:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 51, in backward
10.0.1.101:         train_step(forward_step_func,scaled_loss.backward(retain_graph=retain_graph)
10.0.1.101:
10.0.1.101:   File "/opt/conda/lib/python3.8/site-packages/torch/_tensor.py", line 402, in backward
10.0.1.101:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 607, in train_step
10.0.1.101: Traceback (most recent call last):
10.0.1.101:   File "../pretrain_gpt.py", line 326, in <module>
10.0.1.96:   File "/workdir/2023/Megatron-DeepSpeed/megatron/schedules.py", line 100, in backward_step
10.0.1.97:     model.backward(output_tensor)
10.0.1.99:     model.backward(output_tensor)
10.0.1.99: Traceback (most recent call last):
10.0.1.99:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 9, in wrapped_fn
10.0.1.99:   File "../pretrain_gpt.py", line 326, in <module>
10.0.1.99: Traceback (most recent call last):
10.0.1.99:   File "../pretrain_gpt.py", line 326, in <module>
10.0.1.99:     result = forward_call(*input, **kwargs)
10.0.1.99:   File "/workdir/2023/Megatron-DeepSpeed/megatron/model/fused_layer_norm.py", line 92, in forward
10.0.1.99:     ret_val = func(*args, **kwargs)
10.0.1.99:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1968, in backward
10.0.1.96:     pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
10.0.1.96:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 187, in pretrain
10.0.1.96:     model.backward(output_tensor)
10.0.1.96:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 9, in wrapped_fn
10.0.1.96: Traceback (most recent call last):
10.0.1.96:   File "../pretrain_gpt.py", line 326, in <module>
10.0.1.96:     ret_val = func(*args, **kwargs)
10.0.1.99:     return F.layer_norm(input, self.normalized_shape, self.weight, self.bias, self.eps)
10.0.1.97:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 9, in wrapped_fn
10.0.1.101:     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
10.0.1.96:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1968, in backward
10.0.1.96:     iteration = train(forward_step_func,
10.0.1.99:   File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2509, in layer_norm
10.0.1.97:     self.optimizer.backward(loss, retain_graph=retain_graph)
10.0.1.101:   File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 191, in backward
10.0.1.99:     pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
10.0.1.97:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 9, in wrapped_fn
10.0.1.101:     return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
10.0.1.101:     losses_reduced = forward_backward_func(
10.0.1.101:   File "/workdir/2023/Megatron-DeepSpeed/megatron/schedules.py", line 161, in forward_backward_no_pipelining
10.0.1.101: RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:4! (when checking argument for argument weight in method wrapper__native_layer_norm)
10.0.1.101:     Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
10.0.1.101:   File "/opt/conda/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
10.0.1.99:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 187, in pretrain
10.0.1.97:     ret_val = func(*args, **kwargs)
10.0.1.101:     backward_step(optimizer, input_tensor, output_tensor, output_tensor_grad, model)
10.0.1.99:     self.optimizer.backward(loss, retain_graph=retain_graph)
10.0.1.97:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1968, in backward
10.0.1.101:   File "/workdir/2023/Megatron-DeepSpeed/megatron/schedules.py", line 100, in backward_step
10.0.1.96:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 1034, in train
10.0.1.99:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 9, in wrapped_fn
10.0.1.97:     train_step(forward_step_func,
10.0.1.101:     model.backward(output_tensor)
10.0.1.99:         ret_val = func(*args, **kwargs)iteration = train(forward_step_func,
10.0.1.97:   File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 607, in train_step
10.0.1.101:   File "/opt/conda/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 9, in wrapped_fn
10.0.1.99:
10.0.1.99:       File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 2089, in backward
10.0.1.97:     ret_val = func(*args, **kwargs)
10.0.1.99: return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)  File "/workdir/2023/Megatron-DeepSpeed/megatron/training.py", line 1034, in train
10.0.1.101:     return user_fn(self, *args)
10.0.1.97:       File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 2089, in backward
```
</p>
</details>

Test script
```bash
#!/bin/bash
set -ex

BASE_PATH=XXXXX
DATA_PATH=XXXXX
DS_CONFIG=XXXXX

TP=1
PP=1

MODEL_SIZE=50
GLOBAL_BATCH=256
MICRO_BATCH=8

ZERO_STAGE=3
PA_CPU=true

# Set to cpu for offloading to cpu for larger models
# OFFLOAD_DEVICE="cpu"
# CPU_OPTIM=" --cpu-optimizer"

# Set to none and empty string for no cpu offloading
OFFLOAD_DEVICE="none" 
CPU_OPTIM=" "

if [ "$MODEL_SIZE" = "10" ]; then
NLAYERS=50
HIDDEN=4096
ATTEN_HEADS=16
SEQ_LENGTH=1024
fi

if [ "$MODEL_SIZE" = "50" ]; then
NLAYERS=62
HIDDEN=8192
ATTEN_HEADS=32
SEQ_LENGTH=1024
fi

if [ "$MODEL_SIZE" = "100" ]; then
NLAYERS=125
HIDDEN=8192
ATTEN_HEADS=32
SEQ_LENGTH=1024
fi

OUTPUT_DIR=./log/ds_z${ZERO_STAGE}_nl${NLAYERS}_hs${HIDDEN}_gb${GLOBAL_BATCH}_mb${MICRO_BATCH}
#OUTPUT_DIR=baseline_nl${NLAYERS}_hs${HIDDEN}_gb${GLOBAL_BATCH}_mb${MICRO_BATCH}
mkdir -p $OUTPUT_DIR

cat <<EOT > $DS_CONFIG
{
  "train_batch_size" : $GLOBAL_BATCH,
  "train_micro_batch_size_per_gpu": $MICRO_BATCH,
  "steps_per_print": 1,

  "zero_optimization": {
    "stage": $ZERO_STAGE,
    "overlap_comm": true
  },

  "activation_checkpointing": {
    "partition_activations": true,
    "cpu_checkpointing": $PA_CPU,
    "contiguous_memory_optimization": true
  },

  "aio": {
    "block_size": 1048576,
    "queue_depth": 16,
    "single_submit": false,
    "overlap_events": true,
    "thread_count": 2
  },
  "fp16": {
    "enabled": true
  },
  "wall_clock_breakdown" : true
}
EOT

export NCCL_DEBUG=warn

ds_args=""
ds_args=" --deepspeed ${ds_args}"
ds_args=" --no-pipeline-parallel ${ds_args}" 
ds_args=" --deepspeed_config=$DS_CONFIG ${ds_args}"
ds_args=" --zero-stage=$ZERO_STAGE ${ds_args}"
ds_args=" --deepspeed-activation-checkpointing ${ds_args}"
ds_args=" --partition-activations ${ds_args}"

if [ "$PA_CPU" = "true" ]; then
ds_args=" --checkpoint-in-cpu ${ds_args}"
fi

ds_args=" --synchronize-each-layer ${ds_args}"
ds_args=" --contigious-checkpointing ${ds_args}"


deepspeed --hostfile=./hostfile ../pretrain_gpt.py \
    --tensor-model-parallel-size $TP \
    --pipeline-model-parallel-size $PP \
    --num-layers $NLAYERS \
    --hidden-size $HIDDEN \
    --num-attention-heads $ATTEN_HEADS \
    --seq-length $SEQ_LENGTH \
    --loss-scale 12 \
    --max-position-embeddings $SEQ_LENGTH \
    --micro-batch-size $MICRO_BATCH \
    --global-batch-size $GLOBAL_BATCH \
    --train-iters 15 \
    --lr 6.0e-5 \
    --min-lr 6.0e-6 \
    --lr-decay-style cosine \
    --log-interval 1 \
    --eval-iters 0 \
    --eval-interval 1000 \
    --data-path $DATA_PATH \
    --vocab-file $BASE_PATH/gpt2-vocab.json \
    --merge-file $BASE_PATH/gpt2-merges.txt \
    --save-interval 1000 \
    --split 98,2,0 \
    --clip-grad 1.0 \
    --weight-decay 0.1 \
    --adam-beta1 0.9 \
    --adam-beta2 0.95 \
    --init-method-std 0.006 \
    --fp16 \
    --checkpoint-activations \
    --tensorboard-dir $OUTPUT_DIR \
    $CPU_OPTIM $ds_args \
    --exit-interval 5000 | tee ${OUTPUT_DIR}/output.log


```

---
- [Megatron-DeepSpeed](https://github.com/microsoft/Megatron-DeepSpeed) commit: [57e6439](https://github.com/microsoft/Megatron-DeepSpeed/tree/57e64391037e7ffd9005a87ae7f1d3009bfddaa7)
- ds_report
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [YES] ...... [OKAY]
cpu_adagrad ............ [YES] ...... [OKAY]
cpu_adam ............... [YES] ...... [OKAY]
fused_adam ............. [YES] ...... [OKAY]
fused_lamb ............. [YES] ...... [OKAY]
quantizer .............. [YES] ...... [OKAY]
random_ltd ............. [YES] ...... [OKAY]
sparse_attn ............ [YES] ...... [OKAY]
spatial_inference ...... [YES] ...... [OKAY]
transformer ............ [YES] ...... [OKAY]
stochastic_transformer . [YES] ...... [OKAY]
transformer_inference .. [YES] ...... [OKAY]
utils .................. [YES] ...... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/opt/conda/lib/python3.8/site-packages/torch']
torch version .................... 1.13.0.dev20220719+cu113
deepspeed install path ........... ['/opt/conda/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.8.1, unknown, unknown
torch cuda version ............... 11.3
torch hip version ................ None
nvcc version ..................... 11.3
deepspeed wheel compiled w. ...... torch 1.13, cuda 11.3
```

**Comment by bliu3650** [comment]
Seems the CPU CHECKPOINTING feature is not compatible with TP=1; And the TP>1 is not compatible with ZeRO3 either.

If someone want to try ZeRO + PA + CPU CHECKPOINTING, the ZeRO2 and TP > 1 need to be set.

https://deepspeed.readthedocs.io/en/latest/activation-checkpointing.html
![image](https://user-images.githubusercontent.com/21085266/227164533-dc6b9633-210e-44fb-8208-dd6e8d6d4ae2.png)
