### ISSUE TITLE
RuntimeError: The global rank 0 is not part of the group <torch._C._distributed_c10d.ProcessGroupNCCL object at 0x7fbb8f4817f0>

### ISSUE THREAD

**Issue by Thewillman** [microsoft/Megatron-DeepSpeed#124]
I just use pretrain_gpt.py,but receive such problem
this is my script and library version:
script:
#! /bin/bash
set -e
# Change for multinode config
logname=$(date +'%Y-%m-%d_%H:%M:%S')
if [ -n "$1" ]; then
  logname=$1
fi

MP_SIZE=4
NUM_WORKERS=1
NUM_GPUS_PER_WORKER=4
HIDDEN_SIZE=3072
NUM_ATTN_HEADS=24
NUM_LAYERS=40
BATCHSIZE=16
DATA_PATH=$(cat data_augment.txt)
VOCAB_PATH=vocab.txt
MERGE_PATH=none.txt
CHECKPOINT_PATH=./checkpoints/${logname}

script_path=$(realpath $0)
script_dir=$(dirname $script_path)
config_json="$script_dir/new.json"
#config_json="wyp.json"
# offloads to NVMe
#config_json="$script_dir/ds_zero_stage_infinity_config.json"

#ZeRO Configs
stage=3
reduce_scatter=true
contigious_gradients=true
rbs=50000000
agbs=5000000000

#Activation Checkpointing and Contigious Memory
chkp_layers=1
PA=true
PA_CPU=true
CC=true
SYNCHRONIZE=true
PROFILE=false

# TiledLinear splits, 0 is disable
TILED_LINEAR="true"
TILE_DIM=1

# Megatron Model Parallelism
LOGDIR="tensorboard/failed/${logname}"

#--cpu-optimizer
#--save $CHECKPOINT_PATH \
#        --load $CHECKPOINT_PATH \
gpt_options=" \
        --cpu-optimizer
        --save $CHECKPOINT_PATH \
        --load $CHECKPOINT_PATH \
        --tensor-model-parallel-size ${MP_SIZE} \
        --num-layers $NUM_LAYERS \
        --hidden-size $HIDDEN_SIZE \
        --num-attention-heads ${NUM_ATTN_HEADS} \
        --seq-length 2048 \
        --max-position-embeddings 2048 \
        --micro-batch-size $BATCHSIZE \
	      --train-iters 1500
        --train-tokens 1000000000 \
        --data-path $DATA_PATH \
        --vocab-file $VOCAB_PATH \
        --merge-file $MERGE_PATH \
        --data-impl mmap \
        --split 98,0,2 \
	      --tokenizer-type EncDecTokenizer \
        --distributed-backend nccl \
        --lr 1.5e-4 \
        --lr-decay-style cosine \
        --min-lr 1.0e-5 \
        --weight-decay 1e-2 \
        --clip-grad 1.0 \
        --lr-warmup-fraction 0.01 \
        --checkpoint-activations \
        --log-interval 1 \
        --save-interval 10000 \
        --eval-interval 2000 \
        --eval-iters 10 \
        --fp16 \
        --scattered-embeddings \
        --split-transformers \
        --tensorboard-dir ${LOGDIR} \
	--no-pipeline-parallel
"
deepspeed_options=" \
                --deepspeed \
                --deepspeed_config ${config_json} \
                --zero-stage ${stage} \
                --zero-reduce-bucket-size ${rbs} \
                --zero-allgather-bucket-size ${agbs} \
		--remote-device cpu 
            "

if [ "${contigious_gradients}" = "true" ]; then
  deepspeed_options="${deepspeed_options} \
                --zero-contigious-gradients"
fi

if [ "${reduce_scatter}" = "true" ]; then
  deepspeed_options="${deepspeed_options} \
                --zero-reduce-scatter"
fi

chkp_opt=" \
--deepspeed-activation-checkpointing \
--checkpoint-num-layers ${chkp_layers}"

if [ "${PA}" = "true" ]; then
  chkp_opt="${chkp_opt} --partition-activations"
fi

if [ "${PA_CPU}" = "true" ]; then
  chkp_opt="${chkp_opt} \
        --checkpoint-in-cpu"
fi

if [ "${SYNCHRONIZE}" = "true" ]; then
  chkp_opt="${chkp_opt} \
        --synchronize-each-layer"
fi

if [ "${CC}" = "true" ]; then
  chkp_opt="${chkp_opt} \
        --contigious-checkpointing"
fi

if [ "${PROFILE}" = "true" ]; then
  chkp_opt="${chkp_opt} \
        --profile-backward"
fi

if [ "${TILED_LINEAR}" = "true" ]; then
  tile_opt="${tile_opt} \
        --memory-centric-tiled-linear \
        --tile-factor=${TILE_DIM}"
fi

full_options="${gpt_options} ${deepspeed_options} ${chkp_opt} ${tile_opt}"
run_cmd="deepspeed --num_nodes ${NUM_WORKERS} --num_gpus ${NUM_GPUS_PER_WORKER}  pretrain_gpt.py  ${full_options}  |tee log/failed${logname}.log"

#if [ $(cat wlog/$(log_date).log | tail -1) == "end" ]; then
#  rm wlog/$(log_date).log
#fi

echo ${run_cmd}
eval ${run_cmd}
mv log/failed${logname}.log log/${logname}.log
mv ${LOGDIR} tensorboard/${logname}
set +x

then is my library version:
torch=1.12.1+cu113
deepspeed=0.9.1dev0(get from github)
apex=0.1

**Comment by zte-tcb** [comment]
I some same problem!  When i use **tp>1 + zero3**, error raise. if i use tp=1 + zero3, run success. The error code is:

        with deepspeed.zero.Init(
                    data_parallel_group=mpu.get_data_parallel_group(),
                    remote_device=self.args.zero_offload_param_device,
                    config_dict_or_path=self.args.deepspeed_config,
                    enabled=True, mpu=mpu):
                model_obj = self.model_cls(self.model_config,
                                           topo=model_topo,
                                           input_shape=input_shape)
            )

 **So is there any bug when use tp>1 + zero3?**

Traceback (most recent call last):
  File "/mnt/home/gpt_llama/gpt/train/main.py", line 527, in <module>
    main()
  File "/mnt/home/gpt_llama/gpt/train/main.py", line 484, in main
    model = load_model(args)
  File "/mnt/home/gpt_llama/gpt/train/main.py", line 334, in load_model
    model = AutoModel(model_config, args, models).generate_model()
  File "/mnt/home/gpt_llama/gpt/train/models/auto_model.py", line 62, in generate_model
    model_obj = self.model_cls(self.model_config,
  File "/workspace/bigmodels/DeepSpeed/deepspeed/runtime/zero/partition_parameters.py", line 355, in wrapper
    f(module, *args, **kwargs)
  File "/mnt/home/gpt_llama/gpt/train/models/llama/tp_model.py", line 99, in __init__
    self.embed_tokens = mpu.VocabParallelEmbedding(config.vocab_size,
  File "/workspace/bigmodels/DeepSpeed/deepspeed/runtime/zero/partition_parameters.py", line 363, in wrapper
    self._post_init_method(module)
  File "/workspace/bigmodels/DeepSpeed/deepspeed/runtime/zero/partition_parameters.py", line 754, in _post_init_method
    dist.broadcast(param, 0, self.ds_process_group)
  File "/workspace/bigmodels/DeepSpeed/deepspeed/comm/comm.py", line 123, in log_wrapper
    return func(*args, **kwargs)
  File "/workspace/bigmodels/DeepSpeed/deepspeed/comm/comm.py", line 228, in broadcast
    return cdb.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
  File "/workspace/bigmodels/DeepSpeed/deepspeed/comm/torch.py", line 78, in broadcast
    return torch.distributed.broadcast(tensor=tensor,
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1402, in broadcast
    group_src_rank = get_group_rank(group, src)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 396, in get_group_rank
    raise RuntimeError(f"Global rank {global_rank} is not part of group {group}")
RuntimeError: Global rank 0 is not part of group <torch.distributed.distributed_c10d.ProcessGroupNCCL object at 0x7f47677487b0>

**Comment by zte-tcb** [comment]
This is fixed with https://github.com/microsoft/DeepSpeed/pull/2999
