### ISSUE TITLE
AssertionError: expert parallel group is not initialized

### ISSUE THREAD

**Issue by wangyuxin87** [microsoft/Megatron-DeepSpeed#164]
Traceback (most recent call last):
  File "/DATA/disk2/wangyx/LLaMA-Megatron-DeepSpeed/pretrain_gpt.py", line 326, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/DATA/disk2/wangyx/LLaMA-Megatron-DeepSpeed/megatron/training.py", line 138, in pretrain
    model, optimizer, lr_scheduler = setup_model_and_optimizer(
  File "/DATA/disk2/wangyx/LLaMA-Megatron-DeepSpeed/megatron/training.py", line 520, in setup_model_and_optimizer
    model, optimizer, _, lr_scheduler = deepspeed.initialize(
  File "/DATA/disk1/miniconda3/envs/lm_base/lib/python3.10/site-packages/deepspeed/__init__.py", line 165, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/DATA/disk1/miniconda3/envs/lm_base/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 267, in __init__
    self._configure_distributed_model(model)
  File "/DATA/disk1/miniconda3/envs/lm_base/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1074, in _configure_distributed_model
    module.set_deepspeed_parallelism()
  File "/DATA/disk1/miniconda3/envs/lm_base/lib/python3.10/site-packages/deepspeed/moe/layer.py", line 83, in set_deepspeed_parallelism
    self._create_process_groups()
  File "/DATA/disk1/miniconda3/envs/lm_base/lib/python3.10/site-packages/deepspeed/moe/layer.py", line 97, in _create_process_groups
    self.deepspeed_moe._set_ep_group(groups._get_expert_parallel_group(self.expert_group_name))
  File "/DATA/disk1/miniconda3/envs/lm_base/lib/python3.10/site-packages/deepspeed/utils/groups.py", line 284, in _get_expert_parallel_group
    assert group_name in _EXPERT_PARALLEL_GROUP, \
AssertionError: expert parallel group is not initialized

**Comment by Tokiwa-17** [comment]
@wangyuxin87  hello, I have encountered the same problem, how did you fix it?

**Comment by zdaiot** [comment]
@Tokiwa-17 @wangyuxin87 how did you fix it?

**Comment by marsggbo** [comment]
any update for this issue?
