### ISSUE TITLE
ModuleNotFoundError: No module named 'megatron.p2p_communication'

### ISSUE THREAD

**Issue by YJHMITWEB** [microsoft/Megatron-DeepSpeed#179]
Hi, I am using the latest repo. It seems there are some missing files in the current repo. When I run 
`sh examples_deepspeed/generate_text.sh`, the errors are:
```
deepspeed --num_nodes 1 --num_gpus 1 tools/generate_samples_gpt.py --tensor-model-parallel-size 1 --num-layers 24 --hidden-size 1024 --num-attention-heads 16 --max-position-embeddings 1024 --tokenizer-type GPT2BPETokenizer --fp16 --num-experts 1 --mlp-type standard --micro-batch-size 8 --seq-length 1024 --out-seq-length 1024 --temperature 1.0 --vocab-file gpt2-vocab.json --merge-file gpt2-merges.txt --genfile unconditional_samples.json --top_p 0.9 --log-interval 1 --num-samples 0 --load checkpoints/gpt2_345m --ds-inference
[2023-07-22 10:16:53,001] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-07-22 10:16:54,059] [WARNING] [runner.py:196:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-07-22 10:16:54,076] [INFO] [runner.py:555:main] cmd =/miniconda3/envs/deepspeed/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None tools/generate_samples_gpt.py --tensor-model-parallel-size 1 --num-layers 24 --hidden-size 1024 --num-attention-heads 16 --max-position-embeddings 1024 --tokenizer-type GPT2BPETokenizer --fp16 --num-experts 1 --mlp-type standard --micro-batch-size 8 --seq-length 1024 --out-seq-length 1024 --temperature 1.0 --vocab-file gpt2-vocab.json --merge-file gpt2-merges.txt --genfile unconditional_samples.json --top_p 0.9 --log-interval 1 --num-samples 0 --load checkpoints/gpt2_345m --ds-inference
[2023-07-22 10:16:55,311] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-07-22 10:16:56,299] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0]}
[2023-07-22 10:16:56,299] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=1, node_rank=0
[2023-07-22 10:16:56,299] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2023-07-22 10:16:56,299] [INFO] [launch.py:163:main] dist_world_size=1
[2023-07-22 10:16:56,299] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0
[2023-07-22 10:16:57,556] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "Megatron-DeepSpeed/tools/generate_samples_gpt.py", line 33, in <module>
    from megatron.text_generation_utils import generate_and_write_samples_unconditional
  File "Megatron-DeepSpeed/megatron/text_generation_utils.py", line 29, in <module>
    from megatron.p2p_communication import recv_forward, send_forward
ModuleNotFoundError: No module named 'megatron.p2p_communication'
```

And clearly, that in `text_generation_utils.py`, it tries to import `p2p_communication`, but under `megatron`, there are no such files exists. But in an early branch, there does exist such a file. And I do find several other files also mismatching.

**Comment by YJHMITWEB** [comment]
@conglongli Hi, after I manually add the `p2p_communication.py` from the previous branch, I am still facing some issues. Not sure at this moment, what are the compatible `DeepSpeed` and `Megatron-DeepSpeed` branches that come with a runnable `generate_text.sh` example.

**Comment by conglongli** [comment]
@YJHMITWEB Please provide information about what kind of error you hit after adding the `p2p_communication.py` from the previous branch, and the exact script `generate_text.sh` you used if you made any changes.

**Comment by YJHMITWEB** [comment]
@conglongli Sure. I have tried two combinations.
1. 
I am using `DeepSpeed 0.10.0` and `Megatron-DeepSpeed conglli/moe_test` (This branch comes with a `p2p_communication.py`), and I run `examples/generate_text.sh`:
```
#!/bin/bash
export TORCH_CUDA_ARCH_LIST=8.6+PTX
CHECKPOINT_PATH=/moe/my_example/gpt2_345m
VOCAB_FILE=/moe/my_example/gpt2-vocab.json
MERGE_FILE=/moe/my_example/gpt2-merges.txt
b=8
mp=1
experts=1
nodes=1
gpus=1


use_tutel=""
#use_tutel="--use-tutel"


#ds_inference=""
ds_inference="--ds-inference"

launch_cmd="deepspeed --num_nodes $nodes --num_gpus $gpus"
L=24
H=1024
A=16
#experts1=${experts[$k]}
program_cmd="tools/generate_samples_gpt.py \
       --tensor-model-parallel-size $mp \
       --num-layers $L \
       --hidden-size $H \
       --num-attention-heads $A \
       --max-position-embeddings 1024 \
       --tokenizer-type GPT2BPETokenizer \
       --fp16 \
       --num-experts ${experts} \
       --mlp-type standard \
       --micro-batch-size $b \
       --seq-length 1024 \
       --out-seq-length 1024 \
       --temperature 1.0 \
       --vocab-file $VOCAB_FILE \
       --merge-file $MERGE_FILE \
       --genfile unconditional_samples.json \
       --top_p 0.9 \
       --log-interval 1 \
       --num-samples $((100*$b)) \
       --load $CHECKPOINT_PATH \
       $use_tutel $ds_inference"

echo $launch_cmd $program_cmd
$launch_cmd $program_cmd

```
The only modification I made is changing ` --num-samples 0 ` to ` --num-samples $((100*$b)) ` as I found when submitting jobs to cluster, using ` --num-samples 0` will trigger the interactive mode which requires terminal input.

**Comment by YJHMITWEB** [comment]
@conglongli And the second combination is:
2.
I also tried using the latest branch of `Megatron-DeepSpeed`, where I need to add the `p2p_communication.py`, and then make the following modifications:
(1) changing `Megatron-DeepSpeed/megatron/arguments.py`:
```
group.add_argument('--local-rank', type=int, default=None,
                       help='local rank passed from distributed launcher.')
```
to
```
group.add_argument('--local_rank', type=int, default=None,
                       help='local rank passed from distributed launcher.')
```
otherwise, it will throw errors.
(2)
Adding `export CUDA_DEVICE_MAX_CONNECTIONS=1` to `Megatron-DeepSpeed/examples_deepspeed/generate_text.sh`, otherwise it will throw errors.

and then I run `sh examples_deepspeed/generate_text.sh`, getting the following error:
```
Building extension module scaled_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] /sw/spack/delta-2022-03/apps/gcc/11.2.0-gcc-8.4.1-fxgnsyr/bin/g++ -MMD -MF scaled_masked_softmax.o.d -DTORCH_EXTENSION_NAME=scaled_masked_softmax_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /miniconda3/envs/deepspeed/lib/python3.10/site-packages/torch/include -isystem /miniconda3/envs/deepspeed/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /miniconda3/envs/deepspeed/lib/python3.10/site-packages/torch/include/TH -isystem /miniconda3/envs/deepspeed/lib/python3.10/site-packages/torch/include/THC -isystem /sw/spack/delta-2022-03/apps/cuda/11.6.1-gcc-11.2.0-vglutoe/include -isystem /miniconda3/envs/deepspeed/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -O3 -c /moe/Megatron-DeepSpeed/megatron/fused_kernels/scaled_masked_softmax.cpp -o scaled_masked_softmax.o 
[2/3] /sw/spack/delta-2022-03/apps/cuda/11.6.1-gcc-11.2.0-vglutoe/bin/nvcc  -ccbin /sw/spack/delta-2022-03/apps/gcc/11.2.0-gcc-8.4.1-fxgnsyr/bin/gcc -DTORCH_EXTENSION_NAME=scaled_masked_softmax_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /miniconda3/envs/deepspeed/lib/python3.10/site-packages/torch/include -isystem/miniconda3/envs/deepspeed/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /miniconda3/envs/deepspeed/lib/python3.10/site-packages/torch/include/TH -isystem /miniconda3/envs/deepspeed/lib/python3.10/site-packages/torch/include/THC -isystem /sw/spack/delta-2022-03/apps/cuda/11.6.1-gcc-11.2.0-vglutoe/include -isystem /miniconda3/envs/deepspeed/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -O3 -gencode arch=compute_70,code=sm_70 --use_fast_math -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda -gencode arch=compute_80,code=sm_80 -std=c++14 -c /moe/Megatron-DeepSpeed/megatron/fused_kernels/scaled_masked_softmax_cuda.cu -o scaled_masked_softmax_cuda.cuda.o 
[3/3] /sw/spack/delta-2022-03/apps/gcc/11.2.0-gcc-8.4.1-fxgnsyr/bin/g++ scaled_masked_softmax.o scaled_masked_softmax_cuda.cuda.o -shared -L/miniconda3/envs/deepspeed/lib/python3.10/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda_cu -ltorch_cuda_cpp -ltorch -ltorch_python -L/sw/spack/delta-2022-03/apps/cuda/11.6.1-gcc-11.2.0-vglutoe/lib64 -lcudart -o scaled_masked_softmax_cuda.so
Loading extension module scaled_masked_softmax_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /moe/Megatron-DeepSpeed/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] /sw/spack/delta-2022-03/apps/gcc/11.2.0-gcc-8.4.1-fxgnsyr/bin/g++ -MMD -MF scaled_softmax.o.d -DTORCH_EXTENSION_NAME=scaled_softmax_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /miniconda3/envs/deepspeed/lib/python3.10/site-packages/torch/include -isystem /miniconda3/envs/deepspeed/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /miniconda3/envs/deepspeed/lib/python3.10/site-packages/torch/include/TH -isystem /miniconda3/envs/deepspeed/lib/python3.10/site-packages/torch/include/THC -isystem /sw/spack/delta-2022-03/apps/cuda/11.6.1-gcc-11.2.0-vglutoe/include -isystem /miniconda3/envs/deepspeed/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -O3 -c /moe/Megatron-DeepSpeed/megatron/fused_kernels/scaled_softmax.cpp -o scaled_softmax.o 
[2/3] /sw/spack/delta-2022-03/apps/cuda/11.6.1-gcc-11.2.0-vglutoe/bin/nvcc  -ccbin /sw/spack/delta-2022-03/apps/gcc/11.2.0-gcc-8.4.1-fxgnsyr/bin/gcc -DTORCH_EXTENSION_NAME=scaled_softmax_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /miniconda3/envs/deepspeed/lib/python3.10/site-packages/torch/include -isystem /miniconda3/envs/deepspeed/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /miniconda3/envs/deepspeed/lib/python3.10/site-packages/torch/include/TH -isystem /miniconda3/envs/deepspeed/lib/python3.10/site-packages/torch/include/THC -isystem /sw/spack/delta-2022-03/apps/cuda/11.6.1-gcc-11.2.0-vglutoe/include -isystem /miniconda3/envs/deepspeed/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -O3 -gencode arch=compute_70,code=sm_70 --use_fast_math -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda -gencode arch=compute_80,code=sm_80 -std=c++14 -c /moe/Megatron-DeepSpeed/megatron/fused_kernels/scaled_softmax_cuda.cu -o scaled_softmax_cuda.cuda.o 
[3/3] /sw/spack/delta-2022-03/apps/gcc/11.2.0-gcc-8.4.1-fxgnsyr/bin/g++ scaled_softmax.o scaled_softmax_cuda.cuda.o -shared -L/miniconda3/envs/deepspeed/lib/python3.10/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda_cu -ltorch_cuda_cpp -ltorch -ltorch_python -L/sw/spack/delta-2022-03/apps/cuda/11.6.1-gcc-11.2.0-vglutoe/lib64 -lcudart -o scaled_softmax_cuda.so
Loading extension module scaled_softmax_cuda...
>>> done with compiling and loading fused kernels. Compilation time: 348.999 seconds
building GPT model ...
Traceback (most recent call last):
  File "/moe/Megatron-DeepSpeed/tools/generate_samples_gpt.py", line 168, in <module>
    main()
  File "/moe/Megatron-DeepSpeed/tools/generate_samples_gpt.py", line 124, in main
    model = get_model(model_provider)
  File "/moe/Megatron-DeepSpeed/megatron/training.py", line 335, in get_model
    model = model_provider_func(
  File "/moe/Megatron-DeepSpeed/tools/generate_samples_gpt.py", line 43, in model_provider
    model = GPTModel(num_tokentypes=0, parallel_output=False,
TypeError: GPTModel.__init__() missing 1 required positional argument: 'config'
```

**Comment by lekurile** [comment]
Hi @YJHMITWEB,

Thank you for investigating this further. I've been able to get to the `TypeError: GPTModel.__init__() missing 1 required positional argument: 'config'` error you're seeing.

To get past it, I've added the following code to `model_provider()` in `generate_samples_gpt.py`:
```python
from megatron.arguments import core_transformer_config_from_args
from megatron import get_args

def model_provider(pre_process=True, post_process=True):
    """Build the model."""

    args = get_args()
    config = core_transformer_config_from_args(args)

    print_rank_0('building GPT model ...')
    model = GPTModel(num_tokentypes=0, parallel_output=False,
                     config=config,
                     pre_process=pre_process, post_process=post_process,
                     return_moe_loss=False) # we need to set "return_moe_loss" for the inference_mode
    return model
```

I'm now seeing the following error on the DeepSpeed Inference Engine side:
```
  File "ds/deepspeed/inference/engine.py", line 164, in __init__
    config.tensor_parallel.tp_size = dist.get_world_size(group=self.mpu.get_model_parallel_group())
AttributeError: module 'megatron.mpu' has no attribute 'get_model_parallel_group'
```

I'll continue the investigation on the Inference Engine side.

Thanks,
Lev

**Comment by Vivicai1005** [comment]
> Hi @YJHMITWEB,
> 
> Thank you for investigating this further. I've been able to get to the `TypeError: GPTModel.__init__() missing 1 required positional argument: 'config'` error you're seeing.
> 
> To get past it, I've added the following code to `model_provider()` in `generate_samples_gpt.py`:
> 
> ```python
> from megatron.arguments import core_transformer_config_from_args
> from megatron import get_args
> 
> def model_provider(pre_process=True, post_process=True):
>     """Build the model."""
> 
>     args = get_args()
>     config = core_transformer_config_from_args(args)
> 
>     print_rank_0('building GPT model ...')
>     model = GPTModel(num_tokentypes=0, parallel_output=False,
>                      config=config,
>                      pre_process=pre_process, post_process=post_process,
>                      return_moe_loss=False) # we need to set "return_moe_loss" for the inference_mode
>     return model
> ```
> 
> I'm now seeing the following error on the DeepSpeed Inference Engine side:
> 
> ```
>   File "ds/deepspeed/inference/engine.py", line 164, in __init__
>     config.tensor_parallel.tp_size = dist.get_world_size(group=self.mpu.get_model_parallel_group())
> AttributeError: module 'megatron.mpu' has no attribute 'get_model_parallel_group'
> ```
> 
> I'll continue the investigation on the Inference Engine side.
> 
> Thanks, Lev

Hi lekurile, were you able to find a solution for it? I'm currently dealing with the similar error.

**Comment by lekurile** [comment]
Hi @YJHMITWEB, @Vivicai1005,

I've pushed a PR fixing a number of issues in `Megatron-DeepSpeed` here:
[Fix Megatron Text Generation Issues #188](https://github.com/microsoft/Megatron-DeepSpeed/pull/188)

And verified that the [Megatron 345M text generation server example](https://github.com/microsoft/Megatron-DeepSpeed#gpt-text-generation) is working in the `Megatron-DeepSpeed` repo (was previously broken).

However, `examples_deepspeed/generate_text.sh` is still broken and will require additional development to get working again.

Thanks,
Lev

**Comment by YJHMITWEB** [comment]
@lekurile Thanks for the effort. Do you think we can keep this issue until `examples_deepspeed/generate_text.sh` is fixed?

**Comment by lekurile** [comment]
@YJHMITWEB, yes, I think it makes sense to keep the issue open for now.
