### ISSUE TITLE
when i train llama2 13b,  ImportError: cannot import name 'get_accelerator' from 'deepspeed' 

### ISSUE THREAD

**Issue by alphanlp** [microsoft/Megatron-DeepSpeed#189]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/llmodel/huap/Megatron-DeepSpeed/megatron/__init__.py", line 14, in <module>
    from .initialize  import initialize_megatron
  File "/data/llmodel/huap/Megatron-DeepSpeed/megatron/initialize.py", line 17, in <module>
    from megatron.core import mpu, tensor_parallel
  File "/data/llmodel/huap/Megatron-DeepSpeed/megatron/core/__init__.py", line 1, in <module>
    import megatron.core.parallel_state
  File "/data/llmodel/huap/Megatron-DeepSpeed/megatron/core/parallel_state.py", line 8, in <module>
    from .utils import GlobalMemoryBuffer
  File "/data/llmodel/huap/Megatron-DeepSpeed/megatron/core/utils.py", line 13, in <module>
    from deepspeed import get_accelerator
ImportError: cannot import name 'get_accelerator' from 'deepspeed'

**Comment by wangguojim** [comment]
you neeed to intall a higher version deepspeed

**Comment by ming-afk** [comment]
Could you check if your PyTorch version matches your cuda version from here? https://pytorch.org/get-started/previous-versions/

**Comment by wangguojim** [comment]
已收到
