### ISSUE TITLE
How to run bert with deepspeed?

### ISSUE THREAD

**Issue by MagiaSN** [microsoft/Megatron-DeepSpeed#20]
I run `pretrain_bert.py` with `--deepspeed` and the following error occurs:

```
Traceback (most recent call last):
  File "pretrain_bert.py", line 147, in <module>
    args_defaults={'tokenizer_type': 'BertWordPieceLowerCase'})
  File "/root/Megatron-DeepSpeed/megatron/training.py", line 162, in pretrain
    train_data_iterator, valid_data_iterator)
  File "/root/Megatron-DeepSpeed/megatron/training.py", line 716, in train
    model[0].set_train_batch_size(global_batch_size)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'DeepSpeedEngine' object has no attribute 'set_train_batch_size'
```

If I just comment this line, it gives another error:

```
Traceback (most recent call last):
  File "pretrain_bert.py", line 147, in <module>
    lr_scheduler)
  File "/root/Megatron-DeepSpeed/megatron/training.py", line 396, in train_step
    assert isinstance(model[0], deepspeed.PipelineEngine), model
AssertionError
```

It seems you modified the GPT code in `GPTModelPipe` class to make it work with DeepSpeed, should we do the same to the Bert model?

**Comment by Sakura-gh** [comment]
Have you solve the problem? it seems the repo only adapt the deepspeed for gpt, but not for bert, so how can we run bert with deepspeed?

**Comment by conglongli** [comment]
Hi @MagiaSN and @Sakura-gh, we have added BERT support with example scripts in this PR https://github.com/microsoft/Megatron-DeepSpeed/pull/75 and will merge it soon. Feel free to reopen this issue or create new issue if you have additional questions about this case.
