### ISSUE TITLE
[BUG] Converting LLAMA2 to hf format raise error: KeyError: 'position_embeddings'

### ISSUE THREAD

**Issue by SefaZeng** [microsoft/Megatron-DeepSpeed#211]
I train a tiny LLAMA2 model with `pretrain_llama2_distributed.sh` and try to convert the model to `huggingface transformers` format with `tools/convert_checkpoint/deepspeed_to_transformers.py`. Then it raise error like following:
```
Traceback (most recent call last):
  File "/Megatron-DeepSpeed/tools/convert_checkpoint/deepspeed_to_transformers.py", line 84, in <module>
    main()
  File "/Megatron-DeepSpeed/tools/convert_checkpoint/deepspeed_to_transformers.py", line 57, in main
    output_state_dict = convert_megatron_checkpoint(args, input_state_dict, config)
  File "/usr/local/python/lib/python3.8/site-packages/transformers/models/megatron_gpt2/convert_megatron_gpt2_checkpoint.py", line 138, in convert_megatron_checkpoint
    pos_embeddings = embeddings["position_embeddings"]["weight"]
KeyError: 'position_embeddings'
```

**Comment by SefaZeng** [comment]
I comment out the `position_embeddings` line. I'm not sure if this is the right, I'm guessing that maybe rotary position embedding doesn't have one like position embeddings. 
Then I notice that the size of two FFN weights is inconsistent, the `ffn_dimension` was set to 4096 and I am getting ffn1 weights of `(1024, 8192)` and ffn2 weights of `(4096, 1024)`.

**Comment by SefaZeng** [comment]
> I comment out the `position_embeddings` line. I'm not sure if this is the right, I'm guessing that maybe rotary position embedding doesn't have one like position embeddings. Then I notice that the size of two FFN weights is inconsistent, the `ffn_dimension` was set to 4096 and I am getting ffn1 weights of `(1024, 8192)` and ffn2 weights of `(4096, 1024)`.

Ok, so, the reason for this is LLAMA2 uses `swiglu` as the activation_function, and it's actually a GLU block that uses both matrices with size (1024, 4096) and Megatron merges these two matrices into one.

**Comment by SefaZeng** [comment]
And it seems the `tasks/eval_harness/evaluate.py` is not working.

**Comment by liguodongiot** [comment]
I meet the same error too.

**Comment by SefaZeng** [comment]
> I meet the same error too.

Hi, @liguodongiot. Do you know what is considered a normal perplexity (PPL) value? In my training set, the loss is around 2.0, and the perplexity is around 7.1. Is this normal, or does it indicate that my model has not converged?

I try to use generate_text.sh to debug the inference code, but I can't get the correct result. I am not sure if it's the inference code or my training contributed to this.

**Comment by SefaZeng** [comment]
By adjusting the weight names of `Megatron-Deepspeed` and `Huggingface`, the conversion can be successful. 

The main issue lies in the fact that `swiglu` should actually be two matrices: `up_weight` and `proj_weight.` 

Taking `1024 * 4096` as an example, Deepspeed combines them into a single matrix of `1024 * 8192`. When using TP=2, this weight is split into two `1024 * 4096` matrices, placed on two GPUs, and each GPU performs the `swiglu` operation by its own. This results in the range [0:2048] and [4097:6145] in the 8192 matrix actually accomplishing what should have been done in the range [0:4096]. During testing, manual modification of this part is required. Of course, the simplest solution would be to construct two matrices during training.

**Comment by JJingL** [comment]
> By adjusting the weight names of `Megatron-Deepspeed` and `Huggingface`, the conversion can be successful.
> 
> The main issue lies in the fact that `swiglu` should actually be two matrices: `up_weight` and `proj_weight.`
> 
> Taking `1024 * 4096` as an example, Deepspeed combines them into a single matrix of `1024 * 8192`. When using TP=2, this weight is split into two `1024 * 4096` matrices, placed on two GPUs, and each GPU performs the `swiglu` operation by its own. This results in the range [0:2048] and [4097:6145] in the 8192 matrix actually accomplishing what should have been done in the range [0:4096]. During testing, manual modification of this part is required. Of course, the simplest solution would be to construct two matrices during training.

Could you please show the specific files and code modified？

**Comment by SefaZeng** [comment]
> > By adjusting the weight names of `Megatron-Deepspeed` and `Huggingface`, the conversion can be successful.
> > The main issue lies in the fact that `swiglu` should actually be two matrices: `up_weight` and `proj_weight.`
> > Taking `1024 * 4096` as an example, Deepspeed combines them into a single matrix of `1024 * 8192`. When using TP=2, this weight is split into two `1024 * 4096` matrices, placed on two GPUs, and each GPU performs the `swiglu` operation by its own. This results in the range [0:2048] and [4097:6145] in the 8192 matrix actually accomplishing what should have been done in the range [0:4096]. During testing, manual modification of this part is required. Of course, the simplest solution would be to construct two matrices during training.
> 
> Could you please show the specific files and code modified？

Here are some [scripts](https://drive.google.com/file/d/1suOT4_Xl7sYmqF1s4wKGshdZEFUtGzr6/view?usp=sharing) for converting model to hf format.

**Comment by JJingL** [comment]
> > > By adjusting the weight names of `Megatron-Deepspeed` and `Huggingface`, the conversion can be successful.
> > > The main issue lies in the fact that `swiglu` should actually be two matrices: `up_weight` and `proj_weight.`
> > > Taking `1024 * 4096` as an example, Deepspeed combines them into a single matrix of `1024 * 8192`. When using TP=2, this weight is split into two `1024 * 4096` matrices, placed on two GPUs, and each GPU performs the `swiglu` operation by its own. This results in the range [0:2048] and [4097:6145] in the 8192 matrix actually accomplishing what should have been done in the range [0:4096]. During testing, manual modification of this part is required. Of course, the simplest solution would be to construct two matrices during training.
> > 
> > 
> > Could you please show the specific files and code modified？
> 
> Here are some [scripts](https://drive.google.com/file/d/1TRziFTbdGPSS9QDEUifwcQsUbKZ4mNEH/view?usp=sharing) for converting model to hf format. `convert.sh` is used for transform models trained with TP=1 and PP=1. `convert_tp.sh` is used for TP=2.

thanks for your reply. Have you ever tried to use the converted model to inference? I just use the coverted model to run inference, but get weried answer  like:
