### ISSUE TITLE
Inference/Evaluation example on pretrained BERT-MoE or GPT-MoE

### ISSUE THREAD

**Issue by YJHMITWEB** [microsoft/Megatron-DeepSpeed#214]
Hi, I am wondering if there are any inference examples on pre-trained MoE models. I tried the `generate_text.sh` in the latest repo, but it raises a couple of issues. Namely, I will need to comment out:
```
    # group.add_argument("--local_rank", type=int, default=0,
    #                    help='local_rank')
```
in `generate_samples_gpt.py`, otherwise, it will raise issues. Then I try to run the script, after I type into some prompt, it raises errors again:
```
Context prompt (stop to exit) >>> hello, tell me about DeepSpeed
Traceback (most recent call last):
  File "Megatron-DeepSpeed/tools/generate_samples_gpt.py", line 176, in <module>
    main()
  File "Megatron-DeepSpeed/tools/generate_samples_gpt.py", line 150, in main
    generate_samples_interactive(model)
  File "Megatron-DeepSpeed/megatron/text_generation_utils.py", line 291, in generate_samples_interactive
    for counter, decode_tokens in enumerate(token_stream):
  File "Megatron-DeepSpeed/megatron/text_generation_utils.py", line 422, in get_token_stream
    for tokens, lengths in batch_token_iterator:
  File "Megatron-DeepSpeed/megatron/text_generation_utils.py", line 542, in sample_sequence_batch
    output, layer_past = forward_step(model, tokens2use,
  File "Megatron-DeepSpeed/megatron/text_generation_utils.py", line 466, in forward_step
    output_tensor = model(tokens, position_ids, attention_mask,
  File "python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "Megatron-DeepSpeed/megatron/model/distributed.py", line 58, in forward
    return self.module(*inputs, **kwargs)
  File "python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "Megatron-DeepSpeed/megatron/model/module.py", line 181, in forward
    outputs = self.module(*inputs, **kwargs)
  File "python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: GPTModel.forward() got an unexpected keyword argument 'layer_past'
```

I would like to know that:
1). Are there any pre-trained GPT-MoE checkpoints and inference examples that can be provided? Because I think in `generate_text.sh`, it just uses a `megatron_lm_345m` which does not have MoE (or just 1 expert like regular MLPs).

**Comment by Joeyzhouqihui** [comment]
It is really hard to find pre-trained GPT-MoE checkpoints.

**Comment by jrt-20** [comment]
@YJHMITWEB Have you found any pre-trained GPT-MOE checkpoints and inference examples, I can not run this generate-text.sh when I set experts>1
