### ISSUE TITLE
Cannot Launch Megatron-Deepspeed with Most Recent Deepspeed Version in Azure

### ISSUE THREAD

**Issue by SulRash** [microsoft/Megatron-DeepSpeed#244]
I'm trying to launch Megatron-Deepspeed in an Azure A100 cluster, but I couldn't launch our job using this bash script:

```
#!/bin/bash
set -ex

BASE_PATH="/mnt/azureml/cr/j/de4858f7ed6849e586deb1662a7cd2ab/exe/wd/outputs/Megatron-DeepSpeed/dataset"
DATA_PATH="${BASE_PATH}/test/processed/test.jsonl_text_document"
DS_CONFIG=ds_config.json

TP=1
PP=1
NLAYERS=24
HIDDEN=512

GLOBAL_BATCH=64
MICRO_BATCH=4

ZERO_STAGE=2

OUTPUT_DIR=ds_z${ZERO_STAGE}_nl${NLAYERS}_hs${HIDDEN}_gb${GLOBAL_BATCH}_mb${MICRO_BATCH}
#OUTPUT_DIR=baseline_nl${NLAYERS}_hs${HIDDEN}_gb${GLOBAL_BATCH}_mb${MICRO_BATCH}
mkdir -p $OUTPUT_DIR

cat <<EOT > $DS_CONFIG
{
  "train_batch_size" : $GLOBAL_BATCH,
  "train_micro_batch_size_per_gpu": $MICRO_BATCH,
  "steps_per_print": 1,

  "zero_optimization": {
    "stage": $ZERO_STAGE
  },

  "fp16": {
    "enabled": true,
    "initial_scale_power": 12
  },

  "wall_clock_breakdown" : true
}
EOT

export NCCL_DEBUG=warn 

ds_args=""
ds_args=" --deepspeed ${ds_args}"
ds_args=" --no-pipeline-parallel ${ds_args}" 
ds_args=" --deepspeed_config=$DS_CONFIG ${ds_args}"
ds_args=" --zero-stage=$ZERO_STAGE ${ds_args}"
ds_args=" --deepspeed-activation-checkpointing ${ds_args}"


deepspeed pretrain_gpt.py \
    --tensor-model-parallel-size $TP \
    --pipeline-model-parallel-size $PP \
    --num-layers $NLAYERS \
    --hidden-size $HIDDEN \
    --num-attention-heads 16 \
    --seq-length 256 \
    --loss-scale 12 \
    --max-position-embeddings 1024 \
    --micro-batch-size 4 \
    --global-batch-size 1024 \
    --train-iters 1000 \
    --lr 6.0e-5 \
    --min-lr 6.0e-6 \
    --lr-decay-style cosine \
    --log-interval 1 \
    --eval-iters 40 \
    --eval-interval 1000 \
    --data-path $DATA_PATH \
    --vocab-file $BASE_PATH/gpt2-vocab.json \
    --merge-file $BASE_PATH/gpt2-merges.txt \
    --save-interval 1000 \
    --split 100,0,0 \
    --clip-grad 1.0 \
    --weight-decay 0.1 \
    --adam-beta1 0.9 \
    --adam-beta2 0.95 \
    --init-method-std 0.006 \
    --fp16 \
    --no-bias-dropout-fusion \
    --no-masked-softmax-fusion \
    --checkpoint-activations \
    --tensorboard-dir $OUTPUT_DIR \
    $ds_args \
    --exit-interval 5000 | tee ${OUTPUT_DIR}/output.log
```

This is the docker context we're using (deepspeed version 0.9.5):

```
FROM mcr.microsoft.com/azureml/curated/acpt-pytorch-1.11-cuda11.3:12
USER root:root

RUN apt-get update && apt-get install -y --no-install-recommends openssh-server 
RUN pip install azureml-core
RUN pip install azureml-mlflow

RUN pip install pybind11
RUN pip install regex
RUN pip install deepspeed sentencepiece nltk einops mpi4py
```

After some debugging, we reached our final issue which was:

```Traceback (most recent call last):
  File "pretrain_gpt.py", line 354, in <module>
    pretrain(train_valid_test_datasets_provider,
  File "/mnt/azureml/cr/j/de4858f7ed6849e586deb1662a7cd2ab/exe/wd/outputs/Megatron-DeepSpeed/megatron/training.py", line 137, in pretrain
    model, optimizer, opt_param_scheduler = setup_model_and_optimizer(
  File "/mnt/azureml/cr/j/de4858f7ed6849e586deb1662a7cd2ab/exe/wd/outputs/Megatron-DeepSpeed/megatron/training.py", line 501, in setup_model_and_optimizer
    model = get_model(model_provider_func, model_type)
  File "/mnt/azureml/cr/j/de4858f7ed6849e586deb1662a7cd2ab/exe/wd/outputs/Megatron-DeepSpeed/megatron/training.py", line 337, in get_model
    model = model_provider_func(
  File "pretrain_gpt.py", line 39, in model_provider
    with deepspeed.zero.Init(sequence_data_parallel_group=mpu.get_sequence_data_parallel_group(),
TypeError: __init__() got an unexpected keyword argument 'sequence_data_parallel_group'
```

The fix for this was just changing the deepspeed init argument `sequence_data_parallel_group` to `data_parallel_group`. Is this a deepspeed version mismatch? If so, why isn't this repo using the latest version of deepspeed? I'm trying to train a 7B model using Megatron-Deepspeed, is there any suggestion you can give us.

Can this change get merged into main? I'd love to do a pull request if possible! @jeffra @samadejacobs

**Comment by eyast** [comment]
Good catch - I'd say please push a PR. Thanks for catching this! (PS: I am not from the Deepspeed team)

**Comment by SulRash** [comment]
Submitted the pull request!
