### ISSUE TITLE
[QUESTION] How to convert pretrained MoE model to FP32?

### ISSUE THREAD

**Issue by nikit91** [microsoft/Megatron-DeepSpeed#300]
Hi,
I have a pretrained MoE model and the checkpoint file structure looks like this:
```
.
├── global_step12345
│   ├── expp_rank_0_mp_rank_00_optim_states.pt
│   ├── layer_0_expert_0_mp_rank_00_model_states.pt
│   ├── layer_0_expert_1_mp_rank_00_model_states.pt
│   ├── layer_0_expert_2_mp_rank_00_model_states.pt
│   ├── layer_0_expert_3_mp_rank_00_model_states.pt
│   ├── layer_10_expert_0_mp_rank_00_model_states.pt
│   ├── layer_10_expert_1_mp_rank_00_model_states.pt
│   ├── layer_10_expert_2_mp_rank_00_model_states.pt
│   ├── layer_10_expert_3_mp_rank_00_model_states.pt
│   ├── layer_11_expert_0_mp_rank_00_model_states.pt
│   ├── layer_11_expert_1_mp_rank_00_model_states.pt
│   ├── layer_11_expert_2_mp_rank_00_model_states.pt
│   ├── layer_11_expert_3_mp_rank_00_model_states.pt
│   ├── layer_1_expert_0_mp_rank_00_model_states.pt
│   ├── layer_1_expert_1_mp_rank_00_model_states.pt
│   ├── layer_1_expert_2_mp_rank_00_model_states.pt
│   ├── layer_1_expert_3_mp_rank_00_model_states.pt
│   ├── layer_2_expert_0_mp_rank_00_model_states.pt
│   ├── layer_2_expert_1_mp_rank_00_model_states.pt
│   ├── layer_2_expert_2_mp_rank_00_model_states.pt
│   ├── layer_2_expert_3_mp_rank_00_model_states.pt
│   ├── layer_3_expert_0_mp_rank_00_model_states.pt
│   ├── layer_3_expert_1_mp_rank_00_model_states.pt
│   ├── layer_3_expert_2_mp_rank_00_model_states.pt
│   ├── layer_3_expert_3_mp_rank_00_model_states.pt
│   ├── layer_4_expert_0_mp_rank_00_model_states.pt
│   ├── layer_4_expert_1_mp_rank_00_model_states.pt
│   ├── layer_4_expert_2_mp_rank_00_model_states.pt
│   ├── layer_4_expert_3_mp_rank_00_model_states.pt
│   ├── layer_5_expert_0_mp_rank_00_model_states.pt
│   ├── layer_5_expert_1_mp_rank_00_model_states.pt
│   ├── layer_5_expert_2_mp_rank_00_model_states.pt
│   ├── layer_5_expert_3_mp_rank_00_model_states.pt
│   ├── layer_6_expert_0_mp_rank_00_model_states.pt
│   ├── layer_6_expert_1_mp_rank_00_model_states.pt
│   ├── layer_6_expert_2_mp_rank_00_model_states.pt
│   ├── layer_6_expert_3_mp_rank_00_model_states.pt
│   ├── layer_7_expert_0_mp_rank_00_model_states.pt
│   ├── layer_7_expert_1_mp_rank_00_model_states.pt
│   ├── layer_7_expert_2_mp_rank_00_model_states.pt
│   ├── layer_7_expert_3_mp_rank_00_model_states.pt
│   ├── layer_8_expert_0_mp_rank_00_model_states.pt
│   ├── layer_8_expert_1_mp_rank_00_model_states.pt
│   ├── layer_8_expert_2_mp_rank_00_model_states.pt
│   ├── layer_8_expert_3_mp_rank_00_model_states.pt
│   ├── layer_9_expert_0_mp_rank_00_model_states.pt
│   ├── layer_9_expert_1_mp_rank_00_model_states.pt
│   ├── layer_9_expert_2_mp_rank_00_model_states.pt
│   ├── layer_9_expert_3_mp_rank_00_model_states.pt
│   ├── mp_rank_00_model_states.pt
│   ├── zero_pp_rank_0_mp_rank_00_optim_states.pt
│   ├── zero_pp_rank_1_mp_rank_00_optim_states.pt
│   ├── zero_pp_rank_2_mp_rank_00_optim_states.pt
│   └── zero_pp_rank_3_mp_rank_00_optim_states.pt
├── latest
├── latest_checkpointed_iteration.txt
└── zero_to_fp32.py
```

I want to convert this model to fp32 for further sharing and fine-tuning. However, when I run the generated script `zero_to_fp32.py`, I get the following error:

```
Processing zero checkpoint './global_step12345'
Traceback (most recent call last):
  File "~/checkpoint/dice_exp-gpt-staticgate-moe-ms_1.3B-bs_104-gpus_4-lr_2.0e-4-minlr_2.0e-5-ep-4-mlc-0.01-cap-1.0-drop-true/zero_to_fp32.py", line 587, in <module>
    convert_zero_checkpoint_to_fp32_state_dict(args.checkpoint_dir, args.output_file, tag=args.tag)
  File "~/checkpoint/dice_exp-gpt-staticgate-moe-ms_1.3B-bs_104-gpus_4-lr_2.0e-4-minlr_2.0e-5-ep-4-mlc-0.01-cap-1.0-drop-true/zero_to_fp32.py", line 523, in convert_zero_checkpoint_to_fp32_state_dict
    state_dict = get_fp32_state_dict_from_zero_checkpoint(checkpoint_dir, tag)
  File "~/checkpoint/dice_exp-gpt-staticgate-moe-ms_1.3B-bs_104-gpus_4-lr_2.0e-4-minlr_2.0e-5-ep-4-mlc-0.01-cap-1.0-drop-true/zero_to_fp32.py", line 509, in get_fp32_state_dict_from_zero_checkpoint
    return _get_fp32_state_dict_from_zero_checkpoint(ds_checkpoint_dir)
  File "~/checkpoint/dice_exp-gpt-staticgate-moe-ms_1.3B-bs_104-gpus_4-lr_2.0e-4-minlr_2.0e-5-ep-4-mlc-0.01-cap-1.0-drop-true/zero_to_fp32.py", line 205, in _get_fp32_state_dict_from_zero_checkpoint
    zero_stage, world_size, fp32_flat_groups = parse_optim_states(optim_files, ds_checkpoint_dir)
  File "~/checkpoint/dice_exp-gpt-staticgate-moe-ms_1.3B-bs_104-gpus_4-lr_2.0e-4-minlr_2.0e-5-ep-4-mlc-0.01-cap-1.0-drop-true/zero_to_fp32.py", line 149, in parse_optim_states
    state_dict["optimizer_state_dict"].pop("optimizer_state_dict", None)
KeyError: 'optimizer_state_dict'
```

What could I be doing wrong here? Are the MoE models supposed to be treated differently?

**Comment by BinZhu-ece** [comment]
> layer_0_expert_0_mp_rank_00_model_states.pt

Have you solved this problem? I have encountered the same problem and look forward to your reply

**Comment by BinZhu-ece** [comment]
> Hi, I have a pretrained MoE model and the checkpoint file structure looks like this:
> 
> ```
> .
> ├── global_step12345
> │   ├── expp_rank_0_mp_rank_00_optim_states.pt
> │   ├── layer_0_expert_0_mp_rank_00_model_states.pt
> │   ├── layer_0_expert_1_mp_rank_00_model_states.pt
> │   ├── layer_0_expert_2_mp_rank_00_model_states.pt
> │   ├── layer_0_expert_3_mp_rank_00_model_states.pt
> │   ├── layer_10_expert_0_mp_rank_00_model_states.pt
> │   ├── layer_10_expert_1_mp_rank_00_model_states.pt
> │   ├── layer_10_expert_2_mp_rank_00_model_states.pt
> │   ├── layer_10_expert_3_mp_rank_00_model_states.pt
> │   ├── layer_11_expert_0_mp_rank_00_model_states.pt
> │   ├── layer_11_expert_1_mp_rank_00_model_states.pt
> │   ├── layer_11_expert_2_mp_rank_00_model_states.pt
> │   ├── layer_11_expert_3_mp_rank_00_model_states.pt
> │   ├── layer_1_expert_0_mp_rank_00_model_states.pt
> │   ├── layer_1_expert_1_mp_rank_00_model_states.pt
> │   ├── layer_1_expert_2_mp_rank_00_model_states.pt
> │   ├── layer_1_expert_3_mp_rank_00_model_states.pt
> │   ├── layer_2_expert_0_mp_rank_00_model_states.pt
> │   ├── layer_2_expert_1_mp_rank_00_model_states.pt
> │   ├── layer_2_expert_2_mp_rank_00_model_states.pt
> │   ├── layer_2_expert_3_mp_rank_00_model_states.pt
> │   ├── layer_3_expert_0_mp_rank_00_model_states.pt
> │   ├── layer_3_expert_1_mp_rank_00_model_states.pt
> │   ├── layer_3_expert_2_mp_rank_00_model_states.pt
> │   ├── layer_3_expert_3_mp_rank_00_model_states.pt
> │   ├── layer_4_expert_0_mp_rank_00_model_states.pt
> │   ├── layer_4_expert_1_mp_rank_00_model_states.pt
> │   ├── layer_4_expert_2_mp_rank_00_model_states.pt
> │   ├── layer_4_expert_3_mp_rank_00_model_states.pt
> │   ├── layer_5_expert_0_mp_rank_00_model_states.pt
> │   ├── layer_5_expert_1_mp_rank_00_model_states.pt
> │   ├── layer_5_expert_2_mp_rank_00_model_states.pt
> │   ├── layer_5_expert_3_mp_rank_00_model_states.pt
> │   ├── layer_6_expert_0_mp_rank_00_model_states.pt
> │   ├── layer_6_expert_1_mp_rank_00_model_states.pt
> │   ├── layer_6_expert_2_mp_rank_00_model_states.pt
> │   ├── layer_6_expert_3_mp_rank_00_model_states.pt
> │   ├── layer_7_expert_0_mp_rank_00_model_states.pt
> │   ├── layer_7_expert_1_mp_rank_00_model_states.pt
> │   ├── layer_7_expert_2_mp_rank_00_model_states.pt
> │   ├── layer_7_expert_3_mp_rank_00_model_states.pt
> │   ├── layer_8_expert_0_mp_rank_00_model_states.pt
> │   ├── layer_8_expert_1_mp_rank_00_model_states.pt
> │   ├── layer_8_expert_2_mp_rank_00_model_states.pt
> │   ├── layer_8_expert_3_mp_rank_00_model_states.pt
> │   ├── layer_9_expert_0_mp_rank_00_model_states.pt
> │   ├── layer_9_expert_1_mp_rank_00_model_states.pt
> │   ├── layer_9_expert_2_mp_rank_00_model_states.pt
> │   ├── layer_9_expert_3_mp_rank_00_model_states.pt
> │   ├── mp_rank_00_model_states.pt
> │   ├── zero_pp_rank_0_mp_rank_00_optim_states.pt
> │   ├── zero_pp_rank_1_mp_rank_00_optim_states.pt
> │   ├── zero_pp_rank_2_mp_rank_00_optim_states.pt
> │   └── zero_pp_rank_3_mp_rank_00_optim_states.pt
> ├── latest
> ├── latest_checkpointed_iteration.txt
> └── zero_to_fp32.py
> ```
> 
> I want to convert this model to fp32 for further sharing and fine-tuning. However, when I run the generated script `zero_to_fp32.py`, I get the following error:
> 
> ```
> Processing zero checkpoint './global_step12345'
> Traceback (most recent call last):
>   File "~/checkpoint/dice_exp-gpt-staticgate-moe-ms_1.3B-bs_104-gpus_4-lr_2.0e-4-minlr_2.0e-5-ep-4-mlc-0.01-cap-1.0-drop-true/zero_to_fp32.py", line 587, in <module>
>     convert_zero_checkpoint_to_fp32_state_dict(args.checkpoint_dir, args.output_file, tag=args.tag)
>   File "~/checkpoint/dice_exp-gpt-staticgate-moe-ms_1.3B-bs_104-gpus_4-lr_2.0e-4-minlr_2.0e-5-ep-4-mlc-0.01-cap-1.0-drop-true/zero_to_fp32.py", line 523, in convert_zero_checkpoint_to_fp32_state_dict
>     state_dict = get_fp32_state_dict_from_zero_checkpoint(checkpoint_dir, tag)
>   File "~/checkpoint/dice_exp-gpt-staticgate-moe-ms_1.3B-bs_104-gpus_4-lr_2.0e-4-minlr_2.0e-5-ep-4-mlc-0.01-cap-1.0-drop-true/zero_to_fp32.py", line 509, in get_fp32_state_dict_from_zero_checkpoint
>     return _get_fp32_state_dict_from_zero_checkpoint(ds_checkpoint_dir)
>   File "~/checkpoint/dice_exp-gpt-staticgate-moe-ms_1.3B-bs_104-gpus_4-lr_2.0e-4-minlr_2.0e-5-ep-4-mlc-0.01-cap-1.0-drop-true/zero_to_fp32.py", line 205, in _get_fp32_state_dict_from_zero_checkpoint
>     zero_stage, world_size, fp32_flat_groups = parse_optim_states(optim_files, ds_checkpoint_dir)
>   File "~/checkpoint/dice_exp-gpt-staticgate-moe-ms_1.3B-bs_104-gpus_4-lr_2.0e-4-minlr_2.0e-5-ep-4-mlc-0.01-cap-1.0-drop-true/zero_to_fp32.py", line 149, in parse_optim_states
>     state_dict["optimizer_state_dict"].pop("optimizer_state_dict", None)
> KeyError: 'optimizer_state_dict'
> ```
> 
> What could I be doing wrong here? Are the MoE models supposed to be treated differently?

Have you solved this problem? I have encountered the same problem and look forward to your reply！！！

**Comment by zhengx18** [comment]
I also has this problem,  is there any solution to slove it ?

**Comment by nikit91** [comment]
I haven't looked into it yet. The problem it persists.

**Comment by nikit91** [comment]
@conglongli Could you please point out, where shall one look to convert the MoE checkpoints for further inference / fine-tuning?

**Comment by ShashankHuang** [comment]
Same problem

**Comment by ShashankHuang** [comment]
@nikit91 
Hi,
Have you solve this problem?
