### ISSUE TITLE
ModuleNotFoundError: No module named 'lm_eval.datasets.coqa'

### ISSUE THREAD

**Issue by xwuShirley** [microsoft/Megatron-DeepSpeed#40]
I followed exactly what this said,  https://github.com/microsoft/Megatron-DeepSpeed/blob/gpt3_with_pile_train_eval/examples/MoE/readme_evalharness.md#prerequisites

but it looks like there is problem with the dataset
```
Traceback (most recent call last):
  File "../../tasks/eval_harness/evaluate.py", line 9, in <module>
    from lm_eval import evaluator, tasks, utils
  File "/home/xiaoxiawu/.local/lib/python3.8/site-packages/lm_eval/evaluator.py", line 7, in <module>
    import lm_eval.tasks
                          File "/home/xiaoxiawu/.local/lib/python3.8/site-packages/lm_eval/tasks/__init__.py", line 10, in <module>
    from . import coqa
  File "/home/xiaoxiawu/.local/lib/python3.8/site-packages/lm_eval/tasks/coqa.py", line 14, in <module>
    import lm_eval.datasets.coqa.coqa
ModuleNotFoundError: No module named 'lm_eval.datasets.coqa'
```

it we comment this out, we will have another problem with the lambada and more.. I wonder what's the problem. The image I used is pretty new 
"indexserveregistry.azurecr.io/deepspeed:latest_torch19-cuda11.3-aml-moe" in RR
https://ml.azure.com/allJobs/job/TEE/dltsrr1/4d15a2a5-087d-443d-a11f-767cc0742658?flight=itpmerge

**Comment by xwuShirley** [comment]
python ../../tasks/eval_harness/download.py --task_list hellaswag,lambada,triviaqa,webqs,winogrande,piqa,arc_challenge,arc_easy,openbookqa,race,boolq,cb,copa,rte,wic,wsc,multirc,record,anli_r1,anli_r2,anli_r3,wikitext,logiqa,mathqa,mc_taco,mrpc,prost,pubmedqa,qnli,qqp,sciq,sst,wnli

**Comment by stas00** [comment]
You probably want to report this here: https://github.com/EleutherAI/lm-evaluation-harness - as Deepspeed has nothing to do with it.

I have just run into this same problem with  `lm-eval` bleed edge.  The released version `lm-eval==0.2.0` doesn't have this error.
