### ISSUE TITLE
"RuntimeError: trying to initialize the default process group twice!" error with pretrain_gpt example script

### ISSUE THREAD

**Issue by rraminen** [microsoft/Megatron-DeepSpeed#54]
I am trying to run Megatron-LM GPT2. Previously, I used to run it from https://github.com/microsoft/DeepSpeedExamples/blob/master/megatron/Megatron-LM-v1.1.5-ZeRO3/examples/ds_pretrain_gpt2-zero2.sh repo.

With the current updated repository, I am running into below error with the script, https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples/pretrain_gpt.sh

```
 Traceback (most recent call last):
  File "pretrain_gpt.py", line 276, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/root/Megatron-DeepSpeed/megatron/training.py", line 130, in pretrain
    model, optimizer, lr_scheduler = setup_model_and_optimizer(model_provider, teacher=False)
  File "/root/Megatron-DeepSpeed/megatron/training.py", line 402, in setup_model_and_optimizer
    model = get_model(model_provider_func)
  File "/root/Megatron-DeepSpeed/megatron/training.py", line 265, in get_model
    model = model_provider_func(
  File "pretrain_gpt.py", line 46, in model_provider
    with deepspeed.zero.Init(data_parallel_group=mpu.get_data_parallel_group(),
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 655, in __init__
    init_distributed()
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/comm/comm.py", line 427, in init_distributed
    cdb = TorchBackend(dist_backend, timeout, init_method)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/comm/torch.py", line 35, in __init__
    self.init_process_group(backend, timeout, init_method)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/comm/torch.py", line 38, in init_process_group
    return torch.distributed.init_process_group(backend,
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 563, in init_process_group
    raise RuntimeError("trying to initialize the default process group " "twice!")
RuntimeError: trying to initialize the default process group twice!
```

Image used: pytorch/pytorch:1.11.0-cuda11.3-cudnn8-devel image

Please advise how to run GPT2 model with DeepSpeed.

**Comment by conglongli** [comment]
Hi @rraminen the examples/pretrain_gpt.sh is a very old script from NVIDIA that didn't have DeepSpeed integration. Could you try this script https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples/MoE/ds_pretrain_gpt_350M_dense.sh
