### ISSUE TITLE
Issue loading GPT2 checkpoint: "torch.nn.modules.module.ModuleAttributeError: 'ParallelTransformerLayer' object has no attribute 'self_attention'"

### ISSUE THREAD

**Issue by gcunhase** [microsoft/Megatron-DeepSpeed#82]
# Steps to Reproduce
1. Download model checkpoints and followed set-up as instructed in the [main README](https://github.com/microsoft/Megatron-DeepSpeed#setup).
2. Run docker container.
3. Run `./examples/generate_text.sh` as instructed [here](https://github.com/microsoft/Megatron-DeepSpeed#gpt-text-generation).

# Observed behavior
```
...
>>> done with compiling and loading fused kernels. Compilation time: 0.686 seconds
building GPT model ...
 > number of parameters on (tensor, pipeline) model parallel rank (0, 0): 354871296
 loading checkpoint from /workspace/checkpoints/gpt2_345m at iteration 0
could not find arguments in the checkpoint ...
 checkpoint version 0
Traceback (most recent call last):
  File "tools/generate_samples_gpt.py", line 168, in <module>
    main()
  File "tools/generate_samples_gpt.py", line 127, in main
    _ = load_checkpoint(model, None, None)
  File "/workspace/megatron_deepspeed/megatron/checkpointing.py", line 397, in load_checkpoint
    fix_query_key_value_ordering(model, checkpoint_version)
  File "/workspace/megatron_deepspeed/megatron/checkpointing.py", line 248, in fix_query_key_value_ordering
    fixed_param = _transpose_first_dim(param.data, 3, True, model)
  File "/workspace/megatron_deepspeed/megatron/checkpointing.py", line 205, in _transpose_first_dim
    attention_module = model.language_model.encoder.layers[0].self_attention  # self_attention
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 795, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'ParallelTransformerLayer' object has no attribute 'self_attention'
```

## Solution found (please fix if acceptable)
Update [megatron/checkpointing.py#L204](https://github.com/microsoft/Megatron-DeepSpeed/blob/5e0f373ca512e5d23aab858645860d1f6667a4d1/megatron/checkpointing.py#L204) as shown below:

```python
# Previous
attention_module = model.language_model.encoder.layers[0].self_attention
# Fixed
attention_module = model.language_model.encoder.layers[0].attention
```

# Expected behavior
Able to load an available pre-trained checkpoint.

# System info
Ubuntu 18.04, PyTorch docker (`docker pull nvcr.io/nvidia/pytorch:20.12-py3`), RTX 3090.

**Comment by Dryn** [comment]
I can confirm.

The bug was introduced on Jun 7, 2022 with commit [50b3251536e71aedcba7d0aa4535bdf3f43e4f6b](https://github.com/microsoft/Megatron-DeepSpeed/commit/50b3251536e71aedcba7d0aa4535bdf3f43e4f6b).
