### ISSUE TITLE
How to run use moe on T5?

### ISSUE THREAD

**Issue by YijiaZhao** [microsoft/Megatron-DeepSpeed#89]
When I use MoE in t5_model.py (one card)
```
        self.language_model, self._language_model_key = get_language_model(
            num_tokentypes=num_tokentypes,
            add_pooler=False,
            add_decoder=True,
            encoder_attn_mask_type=AttnMaskType.padding,
            init_method=init_method,
            scaled_init_method=scaled_init_method,
            num_experts=[2 for _ in range(len_exp)])
```
There's no gradient in the experts. The error occurs: 
```
File "/Megatron-DeepSpeed/megatron/optimizer/optimizer.py", line 308, in _copy_model_grads_to_main_grads
    main_param.grad = model_param.main_grad.float()
AttributeError: 'Parameter' object has no attribute 'main_grad'
```

And for(distribute fp16) :
```
RuntimeError    : if torch.is_grad_enabled() and self.reducer._rebuild_buckets():Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
making sure all `forward` function outputs participate in calculating loss.
 ```
without fp16:
```
Traceback (most recent call last):                                                                                                                                                                                 File "./pretrain_t5.py", line 150, in <module>                                                                                                                                                                     pretrain(train_valid_test_datasets_provider, model_provider, forward_step,                                                                                                                                     File "/Megatron-DeepSpeed/megatron/training.py", line 170, in pretrain                                                                                                                                             iteration = train(forward_step_func,                                                                                                                                                                           File "/Megatron-DeepSpeed/megatron/training.py", line 945, in train                                                                                                                                                train_step(forward_step_func,                                                                                                                                                                                  File "/Megatron-DeepSpeed/megatron/training.py", line 597, in train_step                                                                                                                                           update_successful, grad_norm, num_zeros_in_grad = optimizer.step()
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Megatron-DeepSpeed/megatron/optimizer/optimizer.py", line 505, in step
    grad_norm = self.clip_grad_norm(self.clip_grad)
  File "/Megatron-DeepSpeed/megatron/optimizer/optimizer.py", line 91, in clip_grad_norm
    return clip_grad_norm_fp32(params, clip_grad)
  File "/Megatron-DeepSpeed/megatron/optimizer/clip_grads.py", line 61, in clip_grad_norm_fp32
    grad = param.grad.detach()
AttributeError: 'NoneType' object has no attribute 'detach'
```

**Comment by YijiaZhao** [comment]
I know how to run it.

**Comment by XiaoqingNLP** [comment]
@YijiaZhao  hi, how to solve it ? and what lead to this problem ?
